# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170115_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
