# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.Restaurant'),
            preserve_default=False,
        ),
    ]
