# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170206_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='note',
            new_name='order_note',
        ),
        migrations.AddField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
