# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170210_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_leader',
        ),
    ]
