# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170206_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='item',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='note',
        ),
    ]
