# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('orders', '0006_auto_20170209_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('is_leader', models.BooleanField(default=False)),
            ],
            bases=('auth.group',),
        ),
    ]
