# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_ok'),
        ('orders', '0007_ordergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='ordergroup',
            name='is_leader',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='group_restaurant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderformenupic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
