# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20170210_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergroup',
            old_name='group_restaurant',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='leader',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
