# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170214_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='restaurant_name',
            field=models.CharField(default='shit', max_length=20),
            preserve_default=False,
        ),
    ]
