# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordergroup_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='restaurant_name',
        ),
    ]
